language: java

notifications:
  email:
    - admin@zac-h.co.uk
  on_failure: always

after_success: gradle sonarqube -Dsonar.organization=zacdevil10-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_KEY

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar



deploy:
  provider: releases
  file: build/libs/Travis-CI-JUnit-Test.jar
  overwrite: true
  on:
    repo: zacdevil10/Travis-CI-JUnit-Test
    branch: master
    tags: true
