language: java

notifications:
  email:
    - admin@zac-h.co.uk
  on_failure: always

before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar

script:
  - ./gradlew test build

deploy:
  provider: releases
  file: build/libs/Travis-CI-JUnit-Test.jar
  overwrite: true
  on:
    repo: zacdevil10/Travis-CI-JUnit-Test
    branch: master
    tags: true